appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: StTG0R9QwQD23/61geEE9xNypWVwOokj+HRE/39djJmeQRauWSFgXv9bC6tdlIXfFBdf7wtkMFKi9R+olwhujI28UH6uX6clhj0AFPKHNhdloGXOJf7bGZ45qBlYiHL0Iza/xjSlXHkpM595C8yVnw0gLP3qdjFLJqu9SJPxE72SvrAqsplWtjNWY1xdR2c5/saAsASIpTgl+DJAXKIWIR3Sq57Rldnckm3BKE8ABFatguPg91Fh6TGL6EaaEH73MEhg7VdVgt8DoYXLa4YCFOEG8eNGCWWJDzEmwkM/BuHecKv/r01gappnKMwtcNiFzHwn5QX3LxNzbPUmveJHDEPp3xbXHzXoucVoT9AHU4E4HxCaZ55lf9i8SZJGOjl4M9JIzQX6wmSRgy6WMuXSL8PUguKN72l7FMFunjr8JaRSwh/Cr7DMTm8n3wszctL0Aejqp5oo93hAUlL1FAyZZ8gpjl/v5h7F+4R58XOsSEFWYT0nIeY/fo9bqqVELw+6vYaUCOHw4oSHrvqJGxlMmabALBpAhIeV/S7U3XdJOtsHEIUFwKS9brakMO69Awg5ddZdeJs0jUTjvbE6tcyc0Xe3/IrHaI7j9t8auB1kWvjS9q132kiOQmmihFXHy6hEMzaCAVoo5P82rMymH0rdPOynHiKJ7x1taFlWoGADcfY=}
