travis:
  secure:
    BINSTAR_TOKEN: jcj+HgGxaqzvxTBpmggeyGlOpg05TLcyrX0cKc2lS3x4r2Q0CDBiu2QBFF+RvD+AdMpRl/u3/NwtvhvRCAS5x2AbI7ELxbvDNZbWVGzaDgTbEdPHgRb0aEIDn1DkxGXqFSd9G9+IyhjMQiJi4nt/Tf8PPfDuZ5/D9ItVlBWfr1XytZ0QEXJo6XcSmBPmfYN2FDlMfs85VfUMqofodOcozDaimfFyUNG3DcPCTEkDRStuDpAF974ALkZC2iGO23BnHDpMy9onaw54Tn9fvV/A/hK2Ctc4Ne3E3emBEzQf4gzILlHt6n28FkCg6hHN/jW63tq2wM6uL8kBqndn/iQukZ5EjtzLtG9lMj79ODbs9VNpqTW9aDsf8RuixNyRwBPav4CRq+qjiwtwQ24EZhx4Th/wghKAAY7MCJZPuveDbIAqLvo03kFaDvr6KfgEN/UjnMhuPpJxF68MM0aWv/vxq6XK0fOMUZM/8pQpY2u2QfCmUXIdE7f1o4L1BleMPS+gUxnTL6lPsBe1ijGIP0BZOzjy0/Ljb7RVUMzY3YUApLQ5hrmDHaLhJG4YlxTpCeJaRVsYEAkpPqKHBpLkL/N/vkvRrarXbSmDrLc8yMZMoe31eZCvY76DFX11P4HkWFwGRkJAHIWrH7QlDdFmwhdq2XBobmHrFzLFVTGuzjZC8Oo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
